### ISSUE TITLE
Index resets even if write fails

### ISSUE THREAD

**Issue by ponzao** [mysema/luja#2]
Luja does a rollback of the reset only if the exception comes from Lucene. Application exceptions or end of the world situations still end up in a commit.

**Comment by mangolas** [comment]
The basic rollback support is in the works now.

It will do writer rollback on the RuntimeExceptions and later we can add support for noRollbackFor/rollbackFor exceptions ala Hibernate Transactional annotation .

**Comment by mangolas** [comment]
This has been fixed for a while. Now all Exceptions cause rollback
